# Generated by Django 4.2 on 2023-06-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='Collected',
            new_name='collected',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='CollectedApproved',
            new_name='collectedApproved',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='CollectedApprovedBy',
            new_name='collectedApprovedBy',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='Medition',
            new_name='medition',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='UserID',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Cures',
            new_name='cures',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Manufacturer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='SideEffects',
            new_name='sideEffects',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='BioText',
            new_name='bioText',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Date_Of_Birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
